### ISSUE TITLE
Question about realtime priority set in code

### ISSUE THREAD

**Issue by palexander-14** [AOMediaCodec/SVT-AV1#1488]
Hi!

The problem is not common but met quite often on CentOS 7 with kernel 3.10.0-327.36.3.el7.x86_64.
The problem is as follows.
Sometimes it happens when one of the threads (th_x for example) waiting on a mutex or a semaphore other threads (one of which, let's say it's th_y, should release the mutex of the semaphore which is waited by th_x), but the scheduler doesn't provide time for the th_y.
After some time kernel reports 'BUG: soft lockup - CPU#3 stuck for 22s! [process_name:pid]' and the process is kind of hanging. If you force to reschedule the threads, for example by sending SIGSTOP and SIGCONT signals, the app continues to work normally for a while.
This situation is specific to kernel and CPUs with low cores count, 4 for example, and repeatable oftener with more than 2 instances of the encoder.

When I disabled this priority hacking the encoder worked correctly without any hangs.

So, the question is. Why is there real time priority is forced and would not be better to get rid of it, because, you know, when the encoder works the system becomes slowly-responsive?

https://github.com/AOMediaCodec/SVT-AV1/blob/1d3b6c60d01ef104e741f74b1c0359229e6bf4a7/Source/Lib/Encoder/Globals/EbEncHandle.c#L298
https://github.com/AOMediaCodec/SVT-AV1/blob/1d3b6c60d01ef104e741f74b1c0359229e6bf4a7/Source/Lib/Common/Codec/EbThreads.c#L85

**Comment by hassount** [comment]
@palexander-14 thank you for the detailed description, this mechanism is needed to allow the encoder to use multi-threading to it's fullest extent on some linux distribution such as Ubuntu. This lets the Kernel not retire threads if they are not active so that when they are they can take a high priority in the queue. We see a significant CPU Utilization improvement when using such option. 

Now as this seems to be hurting CentOS, we can create a run-time flag for it and make it off by default. Would that work ?

**Comment by 1480c1** [comment]
I personally am for removing the whole setting the thread to real-time for similar reasons as mentioned https://github.com/OpenVisualCloud/SVT-HEVC/pull/564#discussion_r463376204 since when actually running any kind of video encoding or transcoding pipeline, the encoder is not the only thing that is actively running on a system, nor is it usually the highest priority process that is running

**Comment by hassount** [comment]
> tem, nor is it usually the highest priority process that is running

Thank you for the comment, while I agree that it's not the case at all times, it is sometimes as it will allow high compute workloads such as 4k and 8k later on work smoothly while requiring access to the full machine resources. In order to support those workloads, I prefer if we maintain this option for now.

**Comment by palexander-14** [comment]
> @palexander-14 thank you for the detailed description, this mechanism is needed to allow the encoder to use multi-threading to it's fullest extent on some linux distribution such as Ubuntu. This lets the Kernel not retire threads if they are not active so that when they are they can take a high priority in the queue. We see a significant CPU Utilization improvement when using such option.
> 
> Now as this seems to be hurting CentOS, we can create a run-time flag for it and make it off by default. Would that work ?

Well, for me it is not an actual problem, I can handle this by myself as a patch before building the lib on my side.
But if you interested in my opinion, i'd like to see the setting to boost the process priority.

Thanks for the answers.
The issue can be closed if the discussion will no be followed up.

**Comment by silverbacknet** [comment]
I can't imagine this is a Ubuntu vs CentOS problem, more a # of cores problem, since thread priority is all in the kernel anyway. I like the idea of a --realtime-priority option over --disable-realtime-priority, but that's also because I come at it from the perspective of only have 8 or occasionally 16 cores to use, rather than the massively-multithreaded systems often used for SVT.

I've had occasional deadlocks that fit this pattern, though without having tracked them down, it's impossible to say for sure.

**Comment by palexander-14** [comment]
> I can't imagine this is a Ubuntu vs CentOS problem, more a # of cores problem, since thread priority is all in the kernel anyway. 

Well, from my side I can say that I never got hangs on Ubuntu 16.04 or 20.04 on the same hardware.
