### ISSUE TITLE
CI: Stop uploading the same 120 MB sample videos after every run & reduce other wasteful practices

### ISSUE THREAD

**Issue by EwoutH** [AOMediaCodec/SVT-AV1#1578]
_Edit: In this issue I didn't use my best tone and wording, and should have been more constructive. Please see [my comment below](https://github.com/AOMediaCodec/SVT-AV1/issues/1578#issuecomment-727179912)._

This is probably the most wasteful action I have seen in CI in a long time. We are hosting hundreds of gigabytes of identical videos because, meh, who cares, GitHub pays so it's free.

Currently the [CI](https://github.com/AOMediaCodec/SVT-AV1/actions/runs/348666827), [MSVC builds](https://github.com/AOMediaCodec/SVT-AV1/actions/runs/357208104) and [macOS](https://github.com/AOMediaCodec/SVT-AV1/actions/runs/348666826) runs all upload these 120 MB videos each and every CI cycle.

We also host a huge 350 MB vectors file each [MSVC](https://github.com/AOMediaCodec/SVT-AV1/actions/runs/357208104) run. Is this always neccessary.

Also, how does our build matrixes got so huge? 65 runs just can't be right. We have 20 MSVC runs, of which 10 are exactly identical to 10 others, except one of each pair is release and the other is debug. Same for the CI-workflow, which consists an astounding 26 jobs testing every possible compiler and target system in a full-factorial setup.

And since PRs are being merged left and right without passing CI, it's not that we take or use it too seriously.

I think a major CI review and rewrite is necessary, being far more conscious of the resources that are being used and the impact on the environment (read: planet Earth).

Excuse me for the harsh tone, but this just got completely out of hand and isn't even close anymore to best practices.

I also think a dedicated CI / DevOps /testing engineer who has the lead over what is tested when and why could be very useful.

**Comment by hassount** [comment]
@EwoutH 
Thank you for raising the issue, we are in the process of moving all CI and the repo afterwards to Gitlab ci, where we are already working on reducing the amount of uploads and reducing the size of docker files to allow for re-use + many other optimizations as tracked in #1531. We appreciate the help we got from the community of getting the current CI up and running and while we don't have dedicated Devops engineers to get this up and running, we are trying to do the best with whatever we have while focusing on continuing the contributions to the open source.

We always welcome and appreciate contributions especially in the CI aspect of the project as we don't have a lot of expertise in. 

Now in my honest opinion and not speaking on behalf of Intel or AOM: I believe that your tone in this issue is inappropriate as you and others have been through the process of getting this up and running and know very well how this process has been developed. I think that it would have been more appropriate to mention the rather valid issues at hand without accusing this project of **intentionally** wasting resources. I do understand that we had to learn a lot through the process and we're not doing everything right, but we are working on improving every single day to meet the standard and best practices.

**Comment by 1480c1** [comment]
Although I am not claiming the current situation is perfect, if I remember correctly, the main reason why we even have something like this is that I could not find a good way to share those files between all of those jobs as those jobs were split into different files and I could not find a way to set a dependency to another job inside a different file

**Comment by 1480c1** [comment]
I could use your help and opinion on https://github.com/AOMediaCodec/SVT-AV1/pull/1544 and https://gitlab.com/AOMediaCodec/aom-testing as already mentioned that we are trying to see if we can move as much of our CI to gitlab CI

**Comment by EwoutH** [comment]
@hassount Thanks for the reply, the open attitude and good to see it's being worked on. I will try to deliver a contribution to the Gitlab CI myself sometime soon.

I also want to apologize for my harsh tone when opening this issue. While I was truly amazed about the situation, I myself didn't follow best practices and basic human decency by using the tone and the wording. It should have been constructive critism instead of a rant. I will leave the issue open as written originally, because I don't believe in altering communication to hide my own imperfections.

@1480c1 Thanks for all your effort in maintaining and contributing to the build and CI system. I truly appreciate it.

---

That said, I don't think anyone is intentionally wasting resources (and I don't think I actually stated that), but I do think it would be good to care a lot more about resource usage and keep this in mind when writing, reviewing and merging CI PRs. Just when writing code we care about performance and resources, we should when writing CI.

I will look into #1544 very soon!
