### ISSUE TITLE
HDR 8K Resolution Support

### ISSUE THREAD

**Issue by EssenWorkbench** [AOMediaCodec/SVT-AV1#815]
Is there any chance to support HDR(10bit) 8K resolution ?

**Comment by EwoutH** [comment]
To specify this issue a bit more, this is the current error in the CLI output:
```
Error instance 1: Source Width must be less than 4096
Error instance 1: Source Height must be less than 2160
Encoding
Error encoding at channel 1! Check error log file for more details ...
```
The AV1 spec has [two limits](https://aomediacodec.github.io/av1-spec/#symbols-and-abbreviated-terms) for tile size:

| Symbol name    |    Value    | Description                                      |
|----------------|:-----------:|--------------------------------------------------|
| `MAX_TILE_WIDTH` |     4096    | Maximum width of a tile in units of luma samples |
| `MAX_TILE_AREA`  | 4096 * 2304 | Maximum area of a tile in units of luma samples  |

I think they mean a total area of 4096 * 2304 = 9437184 pixels per tile, so a 3072 * 3072 tile should also be possible. But I don't know this for sure.

Anyway, 8K resolutions should be supported if at least 2x2 tiles are used (`-tile-rows 1` and `-tile-rows 1`). Using these parameters the same error is thrown.

@hassount Could you assign someone to enable resolutions higher than 4096*2304 when multiple tiles are used?

**Comment by MaxValenzuela** [comment]
Any update to this? I'm interested in trying it out.

**Comment by hassount** [comment]
Hello all, 
This is not as simple as removing the restriction as currently making the max resolution go up to 8k would break the encoder. There needs to be work done to cleanup the buffers and address any of the crashes that would crash the encoder. we will look into this after the code cleanup effort that we're trying to work on right now as it would help point to the areas of issues.

**Comment by JouMxyzptlk** [comment]
Aw, just stumbled across this when trying it on my last timelapse video...
Question on this though: With 4K up to 17 GB RAM is eaten by SVT, is 64 GB RAM enough for 8k?
For comparison: 32 GB is enough for 9200x5750 x264 --veryslow. 64 GB is enough for 12800x7200 x264. 192 GB is needed for 15360x8640 or 16384x10240 x264 (examples on my homepage).
 If 64 GB is not enough it is not that urgent any more, since my 192 GB machine is a used dual Sandy Bridge Xeon, and SVT-AV1 switches to "[asm level on system : up to c]" on Sandy Bridge and Ivy Bridge - too slow for anything.

**Comment by veikk0** [comment]
To add to this, it's not just 8K that's affected by the current resolution limitation. Things like vertical 4K video and various non-standard resolutions are impacted too.

Just ran into this myself when attempting to encode a video of an unusual resolution (1500x2220).
